stages:
  train:
    cmd: python src/main.py
    deps:
    - src
    - ds
artifacts:
    model:
        path: model.keras
        type: model
        desc: model
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
