name: DVC
on: [push]
# permissions:
#  contents: write
#  pull-requests: write
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run:
          echo "Starting job"
          pip install -r requirements.txt
          dvc pull --verbose
          dvc repro
#          dvc exp run
